// Frontend IPC type barrel.
//
// IPC struct/enum types are GENERATED by ts-rs from the Rust source of truth
// and live in `./types.generated.ts` (committed, CI drift-checked — SB-01/SB-02).
// Do not hand-edit the generated file; change the Rust struct and re-run
// `cargo test --test ts_rs_export`.
//
// This barrel re-exports the generated types and adds the few frontend-only
// types ts-rs cannot generate:
//   - event payloads emitted via inline `app.emit(... json!(...))` (no Rust struct),
//   - string-union enums stored as TEXT on the Rust side (no Rust enum),
//   - the word-diff / selection helpers the frontend computes locally.

export * from './types.generated';

import type {
  UserContent,
  CacheStatus,
  SessionCacheStatus,
  SessionDivergence,
} from './types.generated';

// --- String unions (stored as TEXT in SQLite; no Rust enum SoT) ---

export type VaultItemType = 'Story' | 'Folder' | 'SourceDocument' | 'Image';
export type MessageRole = 'user' | 'model';
export type ContentType = 'json_user' | 'text' | 'blocks';
export type MessageKind = 'story' | 'handover' | 'consulting';
export type FinishReason = 'STOP' | 'MAX_TOKENS' | 'SAFETY' | 'ERROR';

// --- Frontend-only helpers ---

/** Persisted draft per Doc 15 §Drafts; same shape as UserContent. */
export type InputDraft = UserContent;

/** Doc 17 §Selection. Character offsets into `messages.content` (UTF-16 code
 *  units, matching the JS `Selection` API). Frontend-only — never crosses IPC. */
export type GhostwriterSelection = {
  startOffset: number;
  endOffset: number;
  selectedText: string;
};

/** Doc 17 §Diff Display. One span of the word-level LCS diff between the
 *  original message content and the stitched revision. Computed in the frontend. */
export type DiffSpan = { kind: 'unchanged'; text: string } | { kind: 'changed'; text: string };

// --- Event payloads (emitted via inline JSON; no Rust struct SoT) ---

/** Payload of `cache_state_changed` event. */
export type CacheStateChangedPayload = {
  story_id: string;
  status: CacheStatus;
};

/** Payload of `cache_unavailable` event — emitted when a cache create
 *  failed and the send fell back to inline assembly. */
export type CacheUnavailablePayload = {
  story_id: string;
  reason: 'create_failed';
};

/** Payload of `session_cache_state_changed` event. */
export type SessionCacheStateChangedPayload = {
  session_id: string;
  status: SessionCacheStatus;
};

/** Payload of `session_cache_diverged` — surfaces as a non-blocking toast
 *  on session re-entry per Doc 22 §Re-entry. */
export type SessionCacheDivergedPayload = {
  session_id: string;
  divergences: SessionDivergence[];
};

/** Payload of `accordion_state_changed` event. Optional ids let the frontend
 *  re-fetch surgically; full re-fetch is also acceptable. */
export type AccordionStateChangedPayload = {
  story_id: string;
  segment_id: string | null;
  checkpoint_id: string | null;
};

/** Payload of the `settings_changed` event. Frontend re-fetches the cascade
 *  and re-runs `applyTheme` on receipt. `key` is the changed setting key, or
 *  the tab name for a bulk tab-clear, or `'templates'` for a template change. */
export type SettingsChangedPayload = {
  scope: 'app' | 'world';
  key: string;
};
