// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * IPC payload for a closed segment row.
 */
export type AccordionSegment = { id: string, story_id: string, start_cp_id: string, end_cp_id: string, summary: string | null, is_collapsed: boolean, use_summary: boolean, is_stale: boolean, summarised_at: string | null, created_at: string, modified_at: string, };

export type AccordionSnapshotEntry = { segment_id: string, is_collapsed: boolean, summary: string | null, summary_hash: string | null, };

/**
 * Aggregate payload returned by `get_accordion_state`.
 */
export type AccordionState = { checkpoints: Array<Checkpoint>, segments: Array<AccordionSegment>, };

/**
 * Row shape for the right-pane Cache section. Lives here because Doc 03 §IPC
 * names `services/cache.rs::AliveCacheRow` as the authoritative ts-rs source.
 * Story rows have `session_id = None`; consulting rows (added in 6C) carry
 * the active session id + name.
 */
export type AliveCacheRow = { story_id: string, story_name: string, session_id: string | null, session_name: string | null, total_tokens: bigint, expiry_at: string, is_stale: boolean, };

/**
 * Full `app_config.json` payload.
 */
export type AppConfig = { worlds: Array<WorldEntry>, active_world_id: string | null, salt_hex: string, key_check: Sentinel, };

/**
 * Three-state app phase (D-05). Conditional rendering on this field is the
 * only "router" the frontend uses.
 */
export type AppPhase = "onboarding" | "locked" | "workspace";

export type AttachedDocEntry = { doc_id: string, content_hash: string, };

/**
 * IPC payload per Doc 03 §TypeScript Interfaces §Context Caching.
 * Returned by `get_cache_state` and embedded in `cache_state_changed` events.
 */
export type CacheStatus = { cache_name: string | null, expiry_at: string | null, is_stale: boolean, last_cached_message_id: string | null, total_token_count: bigint | null, 
/**
 * `doc_id -> SHA-256 hex` map. Empty when no cache is active.
 */
doc_snapshots: { [key in string]?: string }, };

/**
 * Per Doc 03 §TypeScript Interfaces §Conversation. The IPC payload type for
 * `load_messages` and any place a single message crosses the boundary.
 */
export type ChatMessage = { id: string, story_id: string, session_id: string | null, role: string, content_type: string, content: string, token_count: bigint | null, model_name: string | null, finish_reason: string | null, created_at: string, deleted_at: string | null, user_feedback: string | null, 
/**
 * JSON array string; deserialised on the frontend per Doc 03's
 * `GhostwriterEdit[]` interface. v2.0 Phase 3 stores `'[]'` for every
 * new message — Ghostwriter writes here in Phase 8.
 */
ghostwriter_history: string, kind: string, };

/**
 * IPC payload for a checkpoint row.
 */
export type Checkpoint = { id: string, story_id: string, 
/**
 * `None` only on the start sentinel.
 */
after_message_id: string | null, name: string, is_start: boolean, created_at: string, modified_at: string, };

/**
 * IPC payload per Doc 03 §TypeScript Interfaces. `entry_snapshot` ships as
 * a JSON string; the frontend rarely needs to parse it (the cache rebuild
 * path is backend-only).
 */
export type ConversationSession = { id: string, story_id: string, kind: string, name: string, entry_message_id: string | null, entry_snapshot: string, is_collapsed: boolean, 
/**
 * Populated only for consulting sessions with an active Gemini cache.
 * Handover never sets these; the table CHECK enforces it.
 */
cache_name: string | null, cache_expiry_at: string | null, cache_is_stale: boolean, created_at: string, modified_at: string, };

/**
 * Canonical Ghostwriter edit record per Doc 03 §`GhostwriterEdit` (HB-1).
 * Stored as one element in the `messages.ghostwriter_history` JSON array.
 * Wire-equivalent name in IPC payloads is `GhostwriterEditRecord` (IP-5).
 */
export type GhostwriterEdit = { edited_at: string, original_content: string, new_content: string, instruction: string, selected_text: string, };

/**
 * Returned by `send_ghostwriter_request`. The frontend stitches per Doc 17
 * §Response: `new = before + revised_passage.trim() + after`.
 */
export type GhostwriterResponse = { revised_passage: string, token_count: bigint | null, 
/**
 * `true` iff the user cancelled mid-flight. When true, `revised_passage`
 * is empty and the frontend returns the panel to `selecting` silently.
 */
cancelled: boolean, };

/**
 * Per Doc 03 §IPC Payload and Result Types. Image item metadata.
 */
export type ImageAssetMeta = { width: bigint, height: bigint, mime_type: string, };

/**
 * Single error type for every Tauri command (Doc 05 §LoomError).
 * Eleven variants — adding a twelfth requires a Doc 05 amendment.
 */
export type LoomError = { "kind": "crypto" } & string | { "kind": "database" } & string | { "kind": "not_found" } & string | { "kind": "validation", validation_kind: ValidationKind, key: string | null, reason: string, } | { "kind": "forbidden" } & string | { "kind": "api_error" } & string | { "kind": "cache_create" } & string | { "kind": "rate_limited" } & string | { "kind": "io" } & string | { "kind": "serialization" } & string | { "kind": "internal" } & string;

/**
 * Returned by `revert_ghostwriter_edit` so the frontend can re-render the
 * bubble and decide whether to keep showing the `[Revert]` action.
 */
export type RevertResult = { restored_content: string, remaining_history_len: number, };

/**
 * Returned by `send_message` so the frontend can attach the optimistic user
 * bubble to its persisted id and listen for its model counterpart.
 */
export type SendMessageResult = { user_message_id: string, model_message_id: string, };

/**
 * Payload returned by `send_session_message` — same shape as
 * `SendMessageResult` from `commands/conversation.rs` so the frontend can
 * reuse the pairing logic.
 */
export type SendSessionMessageResult = { user_message_id: string, model_message_id: string, };

/**
 * Sentinel payload stored in `app_config.json`.
 */
export type Sentinel = { nonce_hex: string, ciphertext_hex: string, };

/**
 * Session cache status (Doc 03 §TypeScript Interfaces §Context Caching).
 * Populated only for consulting sessions; handover always has all fields
 * NULL/false (table CHECK enforces).
 */
export type SessionCacheStatus = { cache_name: string | null, expiry_at: string | null, is_stale: boolean, };

/**
 * Doc 22 §Re-entry algorithm — diagnostic record of every snapshot/state
 * disagreement encountered while rebuilding a session prefix. Non-blocking:
 * the prefix is still returned, and the caller surfaces these via a
 * `session_cache_diverged` event for the frontend toast.
 */
export type SessionDivergence = { kind: SessionDivergenceKind, 
/**
 * The id of the message / doc / segment in question. Empty for
 * `PrefixHashMismatch`.
 */
id: string, };

export type SessionDivergenceKind = "missing_story_message" | "missing_attached_doc" | "attached_doc_changed" | "prefix_hash_mismatch";

/**
 * Doc 23 enumerates these as `'handover' | 'consulting'`. Story is *not* a
 * session kind — story is the implicit thread on the story item.
 */
export type SessionKind = "handover" | "consulting";

/**
 * Per Doc 22 §Session Snapshot. JSON-serialised into
 * `conversation_sessions.entry_snapshot`. Phase 4 captures it; Phase 6 reads
 * it on re-entry to rebuild the consulting cache prefix.
 */
export type SessionSnapshot = { schema_version: number, system_instruction: string, story_message_ids: Array<string>, 
/**
 * Empty in Phase 4; Phase 7 populates from `checkpoints` + accordion segments.
 */
accordion_state: Array<AccordionSnapshotEntry>, 
/**
 * Empty in Phase 4; Phase 5 populates from `story_state.context_doc_ids`.
 */
attached_docs: Array<AttachedDocEntry>, prefix_hash: string, };

/**
 * Per-story active-mode state (Doc 23 §Re-opening, §Data Requirements;
 * persisted in `story_state` via the typed `StoryStateKey::ActiveMode` /
 * `ActiveSessionId` accessors). The frontend writes via
 * `set_story_active_mode` from `modeStore` actions and reads via
 * `get_story_active_mode` on story open.
 */
export type StoryActiveMode = { active_mode: string, active_session_id: string | null, };

/**
 * Result of a `countTokens` call. Phase 3 returns just the total — the
 * IPC-facing `TokenEstimate { history, doc, user_turn, total }` shape from
 * Doc 15 is built in the command layer once doc-attachment lands (Phase 5).
 */
export type TokenEstimate = { history_tokens: bigint, doc_tokens: bigint, user_turn_tokens: bigint, total: bigint, };

/**
 * Result returned by `unlock_vault`.
 */
export type UnlockResult = { has_api_key: boolean, auto_lock_secs: bigint, };

/**
 * Parsed `UserContent` per Doc 03 §TypeScript Interfaces. Stored in
 * `messages.content` as JSON when `content_type = 'json_user'`.
 */
export type UserContent = { plot_direction: string, background_information: string, modificators: Array<string>, constraints: string, };

/**
 * Structured discriminator for `LoomError::Validation` (Doc 05).
 */
export type ValidationKind = "generic" | "invalid_setting_value" | "no_baseline" | "protected_sentinel";

/**
 * Per Doc 03 §`items`. IPC payload type for `list_items`, `create_item`,
 * etc. The schema's `content` column is fetched separately (only relevant
 * for SourceDocument bodies — Phase 5).
 */
export type VaultItemMeta = { id: string, parent_id: string | null, item_type: string, item_subtype: string | null, name: string, description: string | null, sort_order: bigint, created_at: string, modified_at: string, deleted_at: string | null, asset_path: string | null, asset_meta: ImageAssetMeta | null, file_api_uri: string | null, };

/**
 * Represents one entry in the worlds registry. Doc 03 §IPC Payload and Result
 * Types — `WorldEntry { id, name, db_path, world_meta_path }`. Older
 * `app_config.json` files written by Phase 1 setup_vault contained an empty
 * `worlds` array, so `world_meta_path` defaults to empty string for forward
 * compatibility (no world entries existed in those files).
 */
export type WorldEntry = { id: string, name: string, db_path: string, world_meta_path: string, };

/**
 * `world_meta.json` payload — matches Doc 03 §`world_meta.json`.
 *
 * Display cache for the World Picker. The encrypted DB is the source of
 * truth for everything except `tags`, which lives only here.
 */
export type WorldMeta = { id: string, name: string, tags: Array<string>, accent_color: string, cover_image_path: string | null, created_at: string, modified_at: string, };

/**
 * Patch payload for `update_world_meta` — Doc 03 §IPC Payload and Result
 * Types. Optional fields; explicit `null` on `cover_image_path` clears it.
 */
export type WorldMetaPatch = { name: string | null, tags: Array<string> | null, accent_color: string | null, 
/**
 * `Some(Some(path))` sets, `Some(None)` clears, `None` leaves untouched.
 * Serialised via `serde` default — frontend sends `null` to clear.
 */
cover_image_path: string | null | null, };
